version: '2'

services:
    sim-global:
        image: chalmersrevere/opendlv-sim-global-amd64:v0.0.5
        command: "/usr/bin/opendlv-sim-global --cid=111 --freq=10 --frame-id=0 --x=-3.0 --yaw=0.0"

    sim-motor-kiwi:
        image: chalmersrevere/opendlv-sim-motor-kiwi-amd64:v0.0.4
        command: "/usr/bin/opendlv-sim-motor-kiwi --cid=111 --freq=100 --frame-id=0"

    sim-ultrasonic-srf08-front:
        image: chalmersrevere/opendlv-sim-ultrasonic-srf08-amd64:v0.0.4
        volumes:
          - ./simulation-map.txt:/opt/simulation-map.txt
        command: "/usr/bin/opendlv-sim-ultrasonic-srf08 --map-file=/opt/simulation-map.txt --x=0.2 --y=0.0 --yaw=0.0 --cid=111 --freq=10 --frame-id=0 --id=0"

    sim-ultrasonic-srf08-rear:
        image: chalmersrevere/opendlv-sim-ultrasonic-srf08-amd64:v0.0.4
        volumes:
          - ./simulation-map.txt:/opt/simulation-map.txt
        command: "/usr/bin/opendlv-sim-ultrasonic-srf08 --map-file=/opt/simulation-map.txt --x=0.2 --y=0.0 --yaw=3.14 --cid=111 --freq=10 --frame-id=0 --id=2"

    sim-sensor-left:
        image: chalmersrevere/opendlv-sim-ultrasonic-srf08-amd64:v0.0.4
        volumes:
          - ./simulation-map.txt:/opt/simulation-map.txt
        command: "/usr/bin/opendlv-sim-ultrasonic-srf08 --map-file=/opt/simulation-map.txt --x=0.0 --y=0.1 --yaw=1.57 --cid=111 --freq=10 --frame-id=0 --id=1"

    sim-sensor-right:
        image: chalmersrevere/opendlv-sim-ultrasonic-srf08-amd64:v0.0.4
        volumes:
          - ./simulation-map.txt:/opt/simulation-map.txt
        command: "/usr/bin/opendlv-sim-ultrasonic-srf08 --map-file=/opt/simulation-map.txt --x=0.0 --y=-0.1 --yaw=-1.57 --cid=111 --freq=10 --frame-id=0 --id=3"

    vehicle-view:
        container_name: opendlv-vehicle-view
        image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.42
        restart: on-failure
        volumes:
        - ./:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        - ./simulation-map.txt:/opt/vehicle-view/simulation-map.txt
        environment:
        - OD4SESSION_CID=111
        - OPENDLV_VEHICLE_VIEW_PLATFORM=Kiwi
        - OPENDLV_VEHICLE_VIEW_ENABLE_KIWI_SIMULATION=1
        ports:
        - "8081:8081"

